<?php  include_once('../includes/navbar.php'); ?>

<main>
    <div class="container p-lg-5 p-4  ">
       
        <div class="pl-lg-5 pr-lg-5 ml-lg-5 mr-lg-5 mb-5 ">
        <h1 class="mb-3">Kro Art Contemporary online</h1><p>Seit 2006 vertritt und präsentiert Kro Art Contemporary erfolgreich einzigartige Positionen und junge, zeitgenössische Künstler aus Österreich und den benachbarten süd- und osteuropäischen Ländern in den Medien Malerei, Graphik, Installationen, Videokunst und Fotografie.</p><p>Der Standort am Getreidemarkt im Zentrum von Wien, in unmittelbarer Nachbarschaft zum Museumsquartier und renommierten Museen, Ausstellungshäusern und Galerien, bieten dafür eine optimale Ausgangsposition. Seit der Neugestaltung 2019 bieten wir nun auch mit dem Artwork Coworking Space Produktions- u. Arbeitsplätze für Kunst u. Design, professionell ausgestattete Seminar- Meeting- und Veranstaltungsräume zur temporären Nutzung und als Treffpunkt für den Feierabend die Artwork Aperobar geöffnet jeweils Mo-Fr 17 h-21 h und bei Veranstaltungen.</p><p>Regelmäßig finden in unseren Räumen am Getreidemarkt Kunst und Designveranstaltungen statt. Über dasaktuelle Programm können Sie sich gerne unter Artwork-space informieren oder unseren Newsletter bestellen. </p><p>Eine ausgesuchte Auswahl an Werken unserer Artists können Sie auch direkt hier auf Kro Art Contemporaryonline erwerben.<br>Die angeführten Preise sind inkl. Mwst jedoch ohne Versandkosten.Zahlungsoptionen, Versand- und Lieferkonditionen werden persönlich mit Ihnen nach erfolgter Bestellung vereinbart.</p></div>
        <div class="textEnglish pl-lg-5 pr-lg-5 ml-lg-5 mr-lg-5 mt-5 ">
        <h1 class="mb-3">Kro Art Contemporary online</h1>
        <p>Since 2006, Kro Art Contemporary has been successfully representing and exhibiting unique artistic positions and young, contemporary artists from Austria and neighboring southern and eastern European countries with works ranging from paintings to graphics, installations, video art and photography.</p><p>On top of it, the location on the Getreidemarkt in the center of Vienna, right next the Museum Quarter and other renowned museums, exhibition houses and galleries, offers an ideal starting point.</p><p>Since the redesign in 2019, we now also offer inside the Artwork Coworking Space a perfect work environmentfor artists and designers, with a fully equipped seminar room and as well meeting and event rooms for temporary use. The new Artwork Aperobar - a meeting point for the after-work relax and for events – is also open Mon-Fri from 5 to 9 p.m.</p><p>Art and design events take place regularly at our space at the Getreidemarkt. You can find out more about the current program on our Artwork-Space website and social media or you can register for our <span>newsletter.</span></p><p>You can also purchase a selected selection of works by our artists here at Kro Art Contemporary online.The prices listed include VAT but do not include shipping costs. Payment options, shipping and delivery conditions will be agreed personally with you after the order has been
        placed.</p></div>
    </div>
</main>
    
<?php include_once('../includes/footer.php') ?>
